### ISSUE TITLE
Cannot connect to query port

### ISSUE THREAD

**Issue by kill0rz** [overshard/docker-teamspeak#27]
Hi,

I cannot connect to the query port. Is there something wrong with my configuration?

docker-compose.yml:

```
  teamspeak:
    image: overshard/teamspeak
    volumes:
        - './data/teamspeak/:/data/'
    ports:
        - '9987:9987/udp'
        - '30033:30033'
        - '10011:10011'
        - '41144:41144'
    restart: always

  teamspeakbot:
    image: galexrt/jts3servermod
    volumes:
        - './teamspeakbot/config/:/jts3servermod/config'
    restart: always
    links:
      - teamspeak
    ports:
        - 8087:8087
```

The server is starting up correctly and I can connect to it via telnet or TS3 client.
But any software using the queryport is giving errors, e.g. the JTS3Servermod bot (as in docker-compose file) or a simple TS3 web-viewer.
